### ISSUE TITLE
base sepolia support

### ISSUE THREAD

**Issue by SweetmanTech** [ourzora/zora-721-contracts#173]
- chainID: 84532
- I have a PR open with deployments already. however, I just need a deployment. If zora team wants to ignore my PR and deploy their own on `base sepolia` I would welcome it

<img width="561" alt="Screenshot 2024-03-15 at 1 14 20 PM" src="https://github.com/ourzora/zora-721-contracts/assets/23249402/dae4d588-4eb7-48aa-b81e-ccd171ee9a1c">

**Comment by iainnash** [comment]
Done in #174
