### ISSUE TITLE
base - mintWithRewards

### ISSUE THREAD

**Issue by sweetmantech** [ourzora/zora-721-contracts#177]
hi zora devs,

just me again
asking for another
base deployment

can you please deploy the latest version of `ERC721DROP_IMPL` on Base mainnet? (`chainId: 8453`)
<img width="1440" alt="Screenshot 2024-04-10 at 3 03 18 PM" src="https://github.com/ourzora/zora-721-contracts/assets/23249402/6ac4d9c3-2e27-41ff-bfce-528c8f4467c8">

latest `ERC721DROP_IMPL`: [0xaDf8fF6a7EA4f028A384D00136fEF0FFfEb39f14] is missing `mintWithRewards` function
(https://thirdweb.com/base/0xaDf8fF6a7EA4f028A384D00136fEF0FFfEb39f14/explorer) 
<img width="1436" alt="Screenshot 2024-04-10 at 3 02 51 PM" src="https://github.com/ourzora/zora-721-contracts/assets/23249402/c7b6743f-783a-4fef-9b75-4126fcdf23b5">

**Comment by iainnash** [comment]
Done.
