### ISSUE TITLE
Using Canvas feature

### ISSUE THREAD

**Issue by AnonVee1** [ourzora/zora-721-contracts#179]
In the canvas feature,

I think it’s better if the word used to ‘imagine’ can be auto-used as the Title.
![IMG_6601](https://github.com/ourzora/zora-721-contracts/assets/142122008/caea47c1-0a13-49c1-8ac7-c69b8a5cceff)

**Comment by iainnash** [comment]
Deprecated this flow so closing this ticket. Thanks for the feedback!
